name: build GDSearch

on:
  push:
    branches:
      - master
      - linux-support

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ["linux-x64", "win-x64"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - run: dotnet --version
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test
      - run: dotnet publish GrimSearch/GrimSearch.csproj --self-contained -r ${{ matrix.runtime }}
