name: build GDSearch

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Setup dotnet 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0

      - run: dotnet restore && dotnet build --no-restore
      - run: dotnet test --no-restore --no-build
      - run: dotnet publish GrimSearch/GrimSearch.csproj --self-contained -r linux-x64
      - run: dotnet publish GrimSearch/GrimSearch.csproj --self-contained -r win-x64
      - name: create zip files
        run: |
          cd $WORKSPACE_DIR/GrimSearch/bin/Release/net8.0/win-x64/publish && zip -r $WORKSPACE_DIR/grimsearch-win-x64-${{ steps.gitversion.outputs.semVer }}.zip .
          cd $WORKSPACE_DIR/GrimSearch/bin/Release/net8.0/linux-x64/publish && zip -r $WORKSPACE_DIR/grimsearch-linux-x64-${{ steps.gitversion.outputs.semVer }}.zip .
        env:
          WORKSPACE_DIR: ${{ github.workspace }}

      - name: create release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: |
            grimsearch-win-x64-${{ steps.gitversion.outputs.semVer }}.zip
            grimsearch-linux-x64-${{ steps.gitversion.outputs.semVer }}.zip
            LICENSE
